### ISSUE TITLE
quotes in uosc 

### ISSUE THREAD

**Issue by OmiChrome** [9beach/mpv-config#1]
hello i see a good script quotes u made 
but i dont use moderX 
i use [UOSC](https://github.com/tomasklaen/uosc/)

So is it posible to get it workign on uosc too ?

**Comment by 9beach** [comment]
USOC has quite different structure. I'm sorry but it's not possible to get it working on uosc by now.

**Comment by NaiveInvestigator** [comment]
Could we potentially make it work with this?
https://github.com/christoph-heinrich/sosc

**Comment by OmiChrome** [comment]
okay i think its not possibe

**Comment by NaiveInvestigator** [comment]
@omaru-ok, you can now use quotes in uosc. Just install this script and you're good to go!

https://github.com/9beach/sosc-and-quotes

**Comment by OmiChrome** [comment]
@NaiveInvestigator  but i think @9beach  would  have opend issue

**Comment by NaiveInvestigator** [comment]
no it is already implemented it so why open the issue? see i reopened it here #2 .

also just try installing that script and see if it works for you or not. It works for me.

Edit: Screenshots for proof ig:
![image](https://user-images.githubusercontent.com/72654596/225626378-9698f196-97ba-444a-a6ac-59d8f39ffc63.png)
![image](https://user-images.githubusercontent.com/72654596/225626393-ed43f850-bf88-4f1e-9fe0-7a94b956244d.png)

Edit - 2: If you're wondering why it works see the second issue.

Edit: - 3 : Also just wanted to mention just in case. Don't delete the uosc script!! You still need that. just install that script along with uosc.
