### ISSUE TITLE
UOSC using quotes

### ISSUE THREAD

**Issue by NaiveInvestigator** [9beach/mpv-config#2]
#1 Reopening issue
that script is literally uosc's idle screen but it was ditched in favour for ease of maintainance.
https://github.com/christoph-heinrich/sosc/

**Comment by 9beach** [comment]
> #1 Reopening issue
> that script is literally uosc's idle screen but it was ditched in favour for ease of maintainance.
> https://github.com/christoph-heinrich/sosc/

I think it's easy to add the quotes to the code of the link. Do you want that?

**Comment by NaiveInvestigator** [comment]
Yes it would be awesome if you could! 

Also have you tried PRing your code to https://github.com/cyl0/Modern ? I think more ppl would love to see this as an option there!

Thank you for consider the feature request!!

**Comment by 9beach** [comment]
I think this kind of feature is not suitable for PRing. Anyway sosc is quite minimal, it's different from uosc. I'm sorry but I ask you again. Is it right that you want the quotes feature in sosc not in usoc?

**Comment by NaiveInvestigator** [comment]
> Anyway sosc is quite minimal,

Yes it is because it is just the idle screen.

 I think if you see this PR you'll get the whole idea.

https://github.com/tomasklaen/uosc/pull/293

> I'm sorry but I ask you again. Is it right that you want the quotes feature in sosc not in usoc?

Yes the quotes feature will in be sosc. Sorry for confusing you :<

**Comment by 9beach** [comment]
@NaiveInvestigator, please check out <https://github.com/9beach/sosc-and-quotes>

**Comment by NaiveInvestigator** [comment]
I get this. I think the message changed but no quotes yet.
![image](https://user-images.githubusercontent.com/72654596/225004127-e6f899ba-fbb3-4024-ba3c-f69aa8389237.png)

**Comment by 9beach** [comment]
@NaiveInvestigator "Save the osc-quotes.txt into your script-opts directory" Did you follow the instruction?

**Comment by NaiveInvestigator** [comment]
![image](https://user-images.githubusercontent.com/72654596/225079963-a75a0e8c-1a53-46f2-ad95-b0ec47a1b53e.png)
this is where it should be saved right?

Edit: I think i got the issue, I'm using the `portable-config` folder that is why this is happening.
we should use `mp.command_native({"expand-path", "~~/"})` instead to make it cross platform.

**Comment by 9beach** [comment]
Thank you @NaiveInvestigator . I did't know `portable_config`. I've fixed it. Please check it out again.

**Comment by NaiveInvestigator** [comment]
omgg it works perfectly!!
![image](https://user-images.githubusercontent.com/72654596/225296811-ef6186f2-b39a-4c06-82af-12ba8a29bf88.png)
But I do have a question, how does one change the message font and it's size. As you can see it is quite big lol. Works a charm tho! :00

Edit: I got it, we need to change the `osd-font` in `mpv.conf`.
Thank you for implementing this!! really really appreciate it!

**Comment by NaiveInvestigator** [comment]
@omaruok

**Comment by NaiveInvestigator** [comment]
![image](https://user-images.githubusercontent.com/72654596/225311458-dacbccdf-0858-4c7e-b894-0285fe091d17.png)
Sorry if you get pinged here but i just had to show this for those JOJO fans who might stumble on this in the future, yes you can do this lmao.

**Comment by 9beach** [comment]
I'm happy you liked it!

**Comment by OmiChrome** [comment]
how do you change the image? of `mpv.cover `

**Comment by NaiveInvestigator** [comment]
sorry didn't get you, I don't have any `mpv.cover`. Are you referring to how i changed the idle message?

**Comment by OmiChrome** [comment]
@NaiveInvestigator  
![image](https://user-images.githubusercontent.com/108952834/226116554-edcbb941-a520-42b0-8072-a4b7fc61255b.png)

i was referring to this

**Comment by NaiveInvestigator** [comment]
ooo I haven't changed it, it was just that by default.

**Comment by NaiveInvestigator** [comment]
o h i'm not so sure sorry. probably it is hardcoded or something.
